apiVersion: v1
kind: Pod
metadata:
  name:  {{ .Values.backend.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceAccountName: {{ .Values.backend.serviceAccountName }}
  containers:
  - name: {{ .Values.backend.name }}
    image: {{ .Values.backend.repository }}
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  tolerations:
  - operator: Exists
    effect: NoSchedule