apiVersion: v1
kind: Pod
metadata:
  name:  {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace }}
spec:
  serviceAccountName: {{ .Values.frontend.serviceAccountName }}
  containers:
  - name: {{ .Values.frontend.name }}
    image: {{ .Values.frontend.repository }}
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  tolerations:
  - operator: Exists
    effect: NoSchedule

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.frontend.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::142180047173:role/s3main-oidc
