apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  labels:
    app: myapp
    type: webserver
spec:  
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: webserver
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - myapp
            topologyKey: kubernetes.io/hostname
      tolerations:
        - key: app
          operator: Equal
          value: kubernetes_trello
          effect: NoSchedule
      nodeSelector:
        reason: kubernetes_task
      containers:
      - name: nginx-container
        image: nginx  
        ports:
          - containerPort: 80
        envFrom:
        - configMapRef:
            name: myapp-config
        - secretRef:
            name: myapp-secret
  replicas: 3
  selector:
    matchLabels:
      type: webserver
