---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: docker-2048-container
        resources:
          requests:
            cpu: 0.5
            memory: "512M"
          limits:
            cpu: 0.5
            memory: "512M"
