---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: docker-2048-container
        securityContext:
          readOnlyRootFilesystem: true
        resources:
          requests:
            cpu: 1.0
            memory: "1024M"
          limits:
            cpu: 1.0
            memory: "1024M"
        
