server:
  global:
    scrape_interval: 15s

  service:
    annotations:
      prometheus.io/scrape: "true"

  persistence:
    enabled: true
    storageClass: "standard"
    size: 10Gi

alertmanager:
  enabled: false

pushgateway:
  enabled: false
